### ISSUE TITLE
fails to build with go 1.10 prerelease

### ISSUE THREAD

**Issue by decathorpe** [gobwas/glob#24]
```
go test github.com/gobwas/glob/syntax/ast
# github.com/gobwas/glob/syntax/ast
(...)/src/github.com/gobwas/glob/syntax/ast/parser_test.go:214: Errorf format %s has arg result of wrong type *ast.Node
FAIL	github.com/gobwas/glob/syntax/ast [build failed]
```

**Comment by gobwas** [comment]
Hi @decathorpe!
Looks like it must work now by 5ccd90ef52e1e632236f7326478d4faa74f99438

**Comment by decathorpe** [comment]
Yes, it compiles fine now. Thanks for fixing this, and for tagging a new release :+1:

**Comment by Lucifer55** [comment]
Transperency just isnt your game,  stick to coearsive orders drones.. Well, as of the moment you made that decision.. You cannot cheat the truth.. You can hide though, no one cares.. Dr. HECKLE..
